/**************************************************
* Class: SurveyConstants
* Author: Soljit - SR
* Date: 2018-08-24
* 
* Description: Defines all constants used on Survey app
*
* V1.0: Initial
*
* 
****************************************************/

public class SurveyConstants {

	public static final string MATRIX_QUES_TYPE = 'Matrix';
    public static final string ACCESS = 'Access';
    public static final string INTEGRATION = 'Integration';
    public static final string AUTOMATION = 'Automation';
    public static final string TRACKING = 'Tracking';
    public static final string TASKSandPM = 'TASKSandPM';
    public static final string REPORTS = 'Reports';
    public static final string ENGLISH_ERROR = 'Please fill all required answers* and contact details*.';
    public static final string FRENCH_ERROR = 'Veuillez répondre à toutes les questions obligatoires* et champs du formulaire*.';
    public static final string NO = 'No (skip those questions)';
    public static final string NON = 'Non (passez à la catégorie suivante)';
    public static final string YES = 'Yes';
    public static final string OUI = 'Oui';
	public static final string SELF_ASSES_TEMPLATE_FR = 'Self_Assessment_French';
    public static final string SELF_ASSES_TEMPLATE_EN = 'Self_Assessment_English';
	public static final string PDF_FR_FILENAME = 'SOLJIT - Auto Évaluation Virage Numérique.pdf';
    public static final string PDF_EN_FILENAME = 'SOLJIT - Self Assessment Digital Transformation.pdf';
    public static final string ENGLISH_LANGUAGE = 'English';
    public static final string FRENCH_LANGUAGE = 'Français';

	public SurveyConstants() {
		
	}
}